name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy SvelteKit App
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the SvelteKit app
      - name: Build SvelteKit app
        run: |
          if ! npm run build; then
            echo "Build failed"
            exit 1
          fi

      # Step 5: Apply D1 migrations
      - name: Apply D1 migrations
        run: npx wrangler d1 migrations apply holdeman --env production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      # Step 6: Deploy to Cloudflare Pages
      - name: Deploy to Cloudflare Pages
        run: npm run deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_PAGES_PROJECT_NAME: holdeman-na
          CF_PAGES_BRANCH: main
